Adding AWS SSM doc to install datacollectors
lacework-dev/scripts pull request #36
Opened 2021-12-01 20:13 UTC by bryancross

Originally created by @ipcrm in a [Gist](https://gist.github.com/ipcrm/f7833ae1ab67996cd422fef7ebc43388).  Using AWS SSM directly has been the second most popular and simple method for installing LW data collectors after just Terraform.  This is the document created by our TF, so shops that don't use TF for whatever reason will find this very useful.

2021-12-01 20:33 UTC, ipcrm requested changes
@bryancross Let's create a README describing how to use it

2021-12-03 17:08 UTC, bryancross commented
@ipcrm Great idea, I'll give it a shot.

2021-12-03 17:25 UTC, bryancross commented
@ipcrm Have a [look](https://github.com/lacework-dev/scripts/blob/add-aws-ssm-doc/AWS-System-Manager/README.md).

2021-12-03 17:36 UTC, ipcrm approved these changes
LGTM!

2021-12-03 17:48 UTC, merged